import { CONFIG_DESC_ZH } from './config-desc.zh';
import { UI_ZH } from './zh';

export type AdminLocale = 'zh' | 'en';

const LOCALE_STORAGE_KEY = 'admin:locale';

function detectLocale(): AdminLocale {
  try {
    const stored = globalThis.localStorage?.getItem(LOCALE_STORAGE_KEY);
    if (stored === 'zh' || stored === 'en') {
      return stored;
    }
    if (globalThis.navigator?.language?.toLowerCase().startsWith('zh')) {
      return 'zh';
    }
  } catch {
    // localStorage can throw in privacy mode; fall through to default
  }
  return 'en';
}

let locale = detectLocale();

export function getLocale(): AdminLocale {
  return locale;
}

export function setLocale(next: AdminLocale) {
  locale = next;
  try {
    globalThis.localStorage?.setItem(LOCALE_STORAGE_KEY, next);
  } catch {
    // best-effort persistence only
  }
}

function interpolate(
  text: string,
  params?: Record<string, string | number>
): string {
  if (!params) {
    return text;
  }
  return text.replace(/\{(\w+)\}/g, (match, name) =>
    name in params ? String(params[name]) : match
  );
}

/**
 * Translate a UI string. The English source text is the dictionary key, so any
 * untranslated string falls back to the original English copy.
 */
export function t(
  text: string,
  params?: Record<string, string | number>
): string {
  const translated = locale === 'zh' ? (UI_ZH[text] ?? text) : text;
  return interpolate(translated, params);
}

/**
 * Translate a config descriptor description by its field path
 * (e.g. `server/name`, `copilot/storage/provider`). `src/config.json` is
 * generated by the server's genconfig script and must stay untouched — the
 * Chinese copy lives in the overlay and unknown fields fall back to the
 * generated English description.
 */
export function translateConfigDesc(field: string, fallback: string): string {
  if (locale === 'zh') {
    return CONFIG_DESC_ZH[field] ?? fallback;
  }
  return fallback;
}
